import Head from 'next/head'
import Navbar from './navbar.jsx'
// import Footer from './footer.jsx'

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>GameHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
      {/* <Footer /> */}
    </>
  )
}